### ISSUE TITLE
Module Not Working

### ISSUE THREAD

**Issue by Rishabh-2802** [TIGMINT/TIGMINT#16]
<img width="805" alt="Screenshot 2021-06-29 at 10 24 37 AM" src="https://user-images.githubusercontent.com/63997779/123739398-39369480-d8c4-11eb-8ab9-e73c665a42e8.png">

**Comment by kiranmuddam** [comment]
@Rishabh-2802 will check this out.

**Comment by kaustubhsh** [comment]
@Rishabh-2802 
This is one of the enhancements required, since the Algorithm of Instagram has changed a little bit, have to bypass a page for user consent.

**Comment by kiranmuddam** [comment]
@Rishabh-2802 @kaustubhsh geo analysis, similar hashtag analysis, top mentions hashtags, username checker working now...
Pushed the fix. Check it out.

**Comment by kiranmuddam** [comment]
Updated twint : pip3 install --user --upgrade git+https://github.com/twintproject/twint.git@origin/master#egg=twint

**Comment by kiranmuddam** [comment]
@kaustubhsh if possible kindly fix issues with sentiment analysis module
