### ISSUE TITLE
Enter Username and Keyword Not working

### ISSUE THREAD

**Issue by OSINTAI** [TIGMINT/TIGMINT#5]
I have tried different handles, but I always for this message.

"404
Maybe you have entered a wrong username? or Username Got deleted? Never existed in the first place?
Let's go home and try from there."

**Comment by kaustubhsh** [comment]
In which module are you facing this error?

**Comment by OSINTAI** [comment]
In "TWITTER ANALYZER" and in "TWITTER: GENERATE SIMILAR HASHTAGS"

I am using Windows 10.

**Comment by kiranmuddam** [comment]
@OSINTAI  can you copy-paste/send screenshots of the console log output?

**Comment by OSINTAI** [comment]
The message is displayed for both modules when using https://tigmint-demo.herokuapp.com/

**Comment by kaustubhsh** [comment]
Hey @OSINTAI,
Heroku has development isuues, it doesn't allow the user to run python script while running the node server.
Please use it on your personal computer and let us know if the error still persist.
Closing this issue now.

**Comment by OSINTAI** [comment]
This is the output after running it locally using #data as hashtag.

*********************************
Express server listening on port 3000 in development mode
#data
{ Error: ModuleNotFoundError: No module named 'aiohttp'
    at PythonShell.parseError (F:\TEST\TIGMINT\node_modules\python-shell\index.js:258:21)
    at terminateIfNeeded (F:\TEST\TIGMINT\node_modules\python-shell\index.js:141:32)
    at ChildProcess.<anonymous> (F:\TEST\TIGMINT\node_modules\python-shell\index.js:133:13)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
    ----- Python Traceback -----
    File "F:\TEST\TIGMINT\Python_Scripts\twitter\similar_hashtags\similar_hashtags.py", line 1, in <module>
      import twint
    File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\twint\__init__.py", line 14, in <module>
      from . import run
    File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\twint\run.py", line 4, in <module>
      from . import datelock, feed, get, output, verbose, storage
    File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\twint\get.py", line 2, in <module>
      import aiohttp
  traceback:
   'Traceback (most recent call last):\r\n  File "F:\\TEST\\TIGMINT\\Python_Scripts\\twitter\\similar_hashtags\\similar_hashtags.py", line 1, in <module>\r\n    import twint\r\n  File "C:\\Users\\USER\\AppData\\Roaming\\Python\\Python37\\site-packages\\twint\\__init__.py", line 14, in <module>\r\n    from . import run\r\n  File "C:\\Users\\USER\\AppData\\Roaming\\Python\\Python37\\site-packages\\twint\\run.py", line 4, in <module>\r\n    from . import datelock, feed, get, output, verbose, storage\r\n  File "C:\\Users\\USER\\AppData\\Roaming\\Python\\Python37\\site-packages\\twint\\get.py", line 2, in <module>\r\n    import aiohttp\r\nModuleNotFoundError: No module named \'aiohttp\'\r\n',
  executable: 'py',
  options: [ '-u' ],
  script:
   'F:\\TEST\\TIGMINT\\Python_Scripts\\twitter\\similar_hashtags\\similar_hashtags.py',
  args: [ '#data' ],
  exitCode: 1 }
**********************************************

**Comment by kiranmuddam** [comment]
@OSINTAI  Please install aiohttp python module. use can use command **"pip3 install aiohttp"** . Also please verify that you installed all the requirements correctly.

**Comment by kiranmuddam** [comment]
@OSINTAI  you can **pip3 install -r requirements.txt** command in the root folder to install all the requirements. Thank you.

**Comment by OSINTAI** [comment]
Thank you.
I have already installed 'pip3 install aiohttp', but the error persists.
I will try the tool in future releases.

**Comment by kaustubhsh** [comment]
@OSINTAI, I have checked it and it's not running on Windows, for now, will try fix the issue in next release.
Thank You

**Comment by kiranmuddam** [comment]
@OSINTAI  For windows users, if the setup fails or application is redirecting to 404 error page always. You can verify the below steps.

Verify all the modules in requirements.txt are successfully installed using pip3 install -r requirements.txt Command . In windows you have to manually install wordcloud module based on your python version.
[WordCloud module download Link](https://www.lfd.uci.edu/~gohlke/pythonlibs/#wordcloud)   |  [ StackOverflow Help Thread](https://stackoverflow.com/questions/41409570/cant-install-wordcloud-in-python-anaconda)
Ex: If you had python 3.6 installed, then you have to install wordcloud‑1.8.0‑cp36‑cp36m‑win_amd64.whl module from the above link.
After installing the wordcloud module, run command pip install -r requirements.txt again to check if all requirements are installed successfully.
Check if all Node requirements are installed using npm install command.
If you still had any problems please open a issue with module name, operating system, input and output and console log. We will try to fix the issue as soon as possible.
